# Generated by Django 6.0.3 on 2026-03-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_profile_image_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
