# Generated by Django 6.0.1 on 2026-03-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
