# Generated by Django 6.0.3 on 2026-03-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_education_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='education_logo/'),
        ),
    ]
