# Generated by Django 6.0.3 on 2026-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_education_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
