# Generated by Django 6.0.3 on 2026-03-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_education_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='gif',
            field=models.URLField(blank=True, help_text='Paste a GIF URL here (e.g., Giphy link)', max_length=500, null=True),
        ),
    ]
